### ISSUE TITLE
🚀 Feature Request: Allow Setting URL for Other OpenAI-Compatible APIs

### ISSUE THREAD

**Issue by hdnh2006** [Royal-lobster/Syncia#79] opened 2024-10-09 13:42 UTC
# IMPORTANT NOTE: This text has been 90% written using Syncia 😉

## Description
It would be highly beneficial for users if the platform allowed setting custom URLs for APIs that are OpenAI-compatible. This feature would enable developers to seamlessly integrate alternative OpenAI-compatible APIs without requiring significant changes to their existing code base.

## Benefits:
Flexibility: Allows users to choose and switch between different OpenAI-compatible APIs based on factors like pricing, uptime, and specific feature sets.
Ease of Integration: Reduces the need for additional code modifications when adapting to different API services.
Business Continuity: Provides a mechanism for fallback options in case of temporary downtime on one API provider.
Encourages Open-Source Innovation: Supports an open ecosystem where users can benefit from various API implementations.

## Proposed Solution:
Introduce a configuration option where users can specify a base URL for API requests. This could be implemented in the settings or configuration file, documented with clear instructions on how to utilize different OpenAI-compatible APIs.

## Considerations:
Ensure compatibility with a wide range of OpenAI API standards.
Maintain security and ensure that switching between URLs does not expose sensitive data inadvertently.

Please let me know if further information or clarification is needed. I'm looking forward to the discussion and possible implementation of this feature!

**Comment by Royal-lobster** [comment] 2024-10-10 10:02
Hii ! Thanks for the issue. Tho i believe this is duplicate of https://github.com/Royal-lobster/Syncia/issues/61 so closing for now cuz we are tracking it there.

**Closed by Royal-lobster** 2024-10-10 10:02 UTC

**Comment by hdnh2006** [comment] 2024-10-10 16:12
Oh nice! thanks for sharing the issue I will follow it
